/*
 Generated by typeshare 1.7.0
*/

export type Provider = {
  id: number;
  title: string;
  secret_id?: string;
  secret_key?: string;
};

export type NewProvider = {
  title: string;
  secret_id?: string;
  secret_key?: string;
};

export type BankInfo = {
  id: string;
  name: string;
};

export type BankConnectionInfo = {
  id: string;
  link: string;
};

export type Account = {
  id: number;
  provider_id: number;
  title: string;
  institution_id?: string;
  bank_connection_id: string;
  account_id?: string;
  iban?: string;
};

export type NewAccount = {
  title: string;
  provider_id: number;
  institution_id: string;
  bank_connection_id: string;
  account_id: string;
};

export type Transaction = {
  id: number;
  title: string;
  debitor_name?: string;
  debitor_iban?: string;
  creditor_name?: string;
  creditor_iban?: string;
  amount: number;
  currency: string;
  date: string;
  remittance_information?: string;
  account_id: number;
};

export type NewTransaction = {
  title: string;
  debitor_name?: string;
  debitor_iban?: string;
  creditor_name?: string;
  creditor_iban?: string;
  amount: number;
  currency: string;
  date: string;
  remittance_information?: string;
  account_id: number;
};

export type Tag = {
  id: number;
  title: string;
};

export type TransactionTag = {
  transaction_id: number;
  tag_id: number;
};

export enum BankingProviders {
  GoCardless = "GoCardless",
}
